spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update #update: 그대로 두는 것, create-drop: 생성할 때 마다 드랍
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
     url: jdbc:postgresql://localhost:15432/emologue-db
     username: emologue-master
     password: emologue-postgres-password

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs  # 기본값: /v3/api-docs
  swagger-ui:
    path: /swagger-ui  # 기본값: /swagger-ui/index.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none


logging:
  level:
    org:
      springframework:
        security: DEBUG
python:
  dictionary-api-url: "http://localhost:5000/analyze"
  predictor-api-url: "http://localhost:5000/predictor"
